config/routes.rb
Rails.application.routes.draw do
  get 'my_goods_nices/index'
  get 'new_arrivals/index'
  get 'popular_ogiris/index'
  get 'my_ogiris/index'
  
  get 'comments/create'
  get 'comments/destroy'

  resources :posts

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :users, only: [:show]

  root  'tops#index'

  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
  end

  resources :posts do
    post 'add' => 'goods#create'
    delete '/add' => 'goods#destroy'
  end

  resources :comments do
    post 'add' => 'nices#create'
    delete '/add' => 'nices#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :ogiri, presence: true, length: { maximum: 55 }
  belongs_to :user
  belongs_to :post
  has_many :nices
  has_many :users, through: :nices
  
  def nice_by?(user)
    nices.where(user_id: user.id).exists?
  end
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/post.rb
class Post < ApplicationRecord
  validates :ogiri, presence: true, length: { maximum: 55 }
  validates :img,   presence: true

  mount_uploader :img, ImgUploader

  belongs_to :user
  
  has_many :comments, dependent: :destroy
  has_many :goods,    dependent: :destroy
  has_many :users, through: :goods
  has_many :users, through: :nices

  scope :created_desc, -> { order(created_at: :desc) } 
  scope :populars,     -> { order(popularcount: :desc).limit(30) }

  def good_by?(user)
    goods.where(user_id: user.id).exists?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts
  has_many :goods, dependent: :destroy
  has_many :good_posts, through: :goods, source: :post
  has_many :nices, dependent: :destroy
  has_many :nice_comments, through: :nices, source: :comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      count = @post.popularcount + 3
      @post.update(popularcount: count)
      redirect_to request.referer
    else
      flash[:alert] = '大喜利の投稿に失敗しました'
      redirect_to request.referer
    end
  end

  #コメント機能には削除なしに今のところはしている
  # def destroy
  #   @post = Post.find(params[:post_id])
  #   @comment = Comment.find(params[:id])
  #   @comment.destroy
  #   count = @post.popularcount - 3
  #   @post.update(popularcount: count)
  #flash[:alert] = '大喜利の投稿を削除しました'
  #   redirect_to request.referer
  # end
  

  private

    def comment_params
      params.require(:comment).permit(:ogiri)
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    good = Good.new(user_id: current_user.id, post_id: @post.id)
    good.save
    count = @post.popularcount + 1
    @post.update(popularcount: count)
  end

  def destroy
    good = Good.find_by(user_id: current_user.id, post_id: @post.id)
    good.delete
    count = @post.popularcount - 1
    @post.update(popularcount: count)
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/my_ogiris_controller.rb
class MyOgirisController < PostsController
  def index
    @posts = current_user.posts.all
  end
end

app/controllers/nices_controller.rb
class NicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment

  def create
    nice = Nice.new(user_id: current_user.id, comment_id: @comment.id)
    nice.save
  end
  
  def destroy
    nice = Nice.find_by(user_id: current_user.id, comment_id: @comment.id)
    nice.delete
  end

  private
  def set_comment
    @comment = Comment.find(params[:comment_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
    @comments = @post.comments
  end


  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      flash[:alert] = '変顔大喜利の投稿に失敗しました'
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "削除が完了しました"
    redirect_to posts_path
  end








  private
    def post_params
      params.require(:post).permit(:ogiri, :img, :popularcount)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/my_goods_nices_helper.rb
module MyGoodsNicesHelper
end

app/helpers/my_ogiris_helper.rb
module MyOgirisHelper
end

app/helpers/new_arrivals_helper.rb
module NewArrivalsHelper
end

app/helpers/popular_ogiris_helper.rb
module PopularOgirisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/goods/_good.html.erb
<% if post.good_by?(current_user) %>
    <%= link_to(post_add_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}") do %>
        <i class="fas fa-heart icon-btn liked">
            <%= post.goods.count %>
        </i>
    <% end %>
<% else %>
    <%= link_to(post_add_path(post), method: :post, remote: true, id: :"like-button-#{post.id}") do %>
        <i class="far fa-heart icon-btn not-like">
            <%= post.goods.count %>
        </i>
    <% end %>
<% end %>

app/views/goods/create.js.erb
$('#post-like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "goods/good", locals: { post: @post }) %>")

app/views/goods/destroy.js.erb
$('#post-like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "goods/good", locals: { post: @post }) %>")

app/views/posts/_camera.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
canvas, video{
    border: 1px solid gray;
}
</style>
</head>
<body>

<h1>今すぐに変顔撮影</h1>

<video id="camera" width="400" height="300"></video>
<canvas id="picture" width="400" height="300"></canvas>
<form>
<button type="button" id="shutter">撮影する</button>
<button onclick="saveCanvas('png');">この変顔を保存</button>
</form>

<audio id="se" preload="auto">
</audio>

<script>
window.onload = () => {
const video  = document.querySelector("#camera");
const canvas = document.querySelector("#picture");
const se     = document.querySelector('#se');

/** カメラ設定 */
const constraints = {
    audio: false,
    video: {
    width: 400,
    height: 300,
    facingMode: "user"   // フロントカメラを利用する
    // facingMode: { exact: "environment" }  // リアカメラを利用する場合
    }
};

/**
* カメラを<video>と同期
*/
navigator.mediaDevices.getUserMedia(constraints)
.then( (stream) => {
    video.srcObject = stream;
    video.onloadedmetadata = (e) => {
    video.play();
    };
})
.catch( (err) => {
    console.log(err.name + ": " + err.message);
});

/**
* シャッターボタン
*/
document.querySelector("#shutter").addEventListener("click", () => {
    const ctx = canvas.getContext("2d");

    // 演出的な目的で一度映像を止めてSEを再生する
    video.pause();  // 映像を停止
    se.play();      // シャッター音
    setTimeout( () => {
    video.play();    // 0.5秒後にカメラ再開
    }, 500);

    // canvasに画像を貼り付ける
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height); 
});
};

// canvas上のイメージを保存
function saveCanvas(saveType){
    var imageType = "image/png";
    var fileName = "my_hengao.png";
    var canvas = document.getElementById("picture");
    // base64エンコードされたデータを取得 「data:image/png;base64,iVBORw0k～」
    var base64 = canvas.toDataURL(imageType);
    // base64データをblobに変換
    var blob = Base64toBlob(base64);
    // blobデータをa要素を使ってダウンロード
    saveBlob(blob, fileName);
}

// Base64データをBlobデータに変換
function Base64toBlob(base64)
{
    // カンマで分割して以下のようにデータを分ける
    // tmp[0] : データ形式（data:image/png;base64）
    // tmp[1] : base64データ（iVBORw0k～）
    var tmp = base64.split(',');
    // base64データの文字列をデコード
    var data = atob(tmp[1]);
    // tmp[0]の文字列（data:image/png;base64）からコンテンツタイプ（image/png）部分を取得
	var mime = tmp[0].split(':')[1].split(';')[0];
    //  1文字ごとにUTF-16コードを表す 0から65535 の整数を取得
	var buf = new Uint8Array(data.length);
	for (var i = 0; i < data.length; i++) {
        buf[i] = data.charCodeAt(i);
    }
    // blobデータを作成
	var blob = new Blob([buf], { type: mime });
    return blob;
}

// 画像のダウンロード
function saveBlob(blob, fileName)
{
    var url = (window.URL || window.webkitURL);
    // ダウンロード用のURL作成
    var dataUrl = url.createObjectURL(blob);
    // イベント作成
    var event = document.createEvent("MouseEvents");
    event.initMouseEvent("click", true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    // a要素を作成
    var a = document.createElementNS("http://www.w3.org/1999/xhtml", "a");
    // ダウンロード用のURLセット
    a.href = dataUrl;
    // ファイル名セット
    a.download = fileName;
    // イベントの発火
    a.dispatchEvent(event);
}
</script>
</body>
</html>

app/views/posts/_new.html.erb
<div class="container">    
    <h3>自分で大喜利</h3>
    <%= form_with model: @post do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :img, "変顔を表示！" %><br />
        <%= f.file_field :img %><br /> 

        <%= f.label :ogiri, "大喜利をしよう！" %><br />
        <%= f.text_field :ogiri, autocomplete: 'off' %>
        
        <%= f.submit :"変顔大喜利を投稿" %>

    <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">    
    <h3>変顔大喜利を編集</h3>
    <%= form_for @post do |f| %>

        <%= image_tag @post.img.to_s, size: "400"  %><br />

        <%= f.label :大喜利をしよう！ %><br />
        <%= f.text_field :ogiri, autocomplete: 'off' %>
        
        <%= f.submit :"変顔大喜利を投稿" %>

    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
    <% if current_user %>
    <%= "変顔大喜利へようこそ#{current_user.username}さん" %><br />
    <% end %>
    <%= link_to "ユーザー情報設定はこちら", edit_user_registration_path %>
    <div class="hidden_box">
        <label for="label1">今すぐに変顔を撮影</label>
        <input type="checkbox" id="label1"/>
        <div class="hidden_show">
            <%= render 'camera' %>
        </div>
    </div>
    <%= render 'new' %>
    <%= link_to "自分の大喜利を見る", my_ogiris_index_path %><br />
    <%= link_to "人気", popular_ogiris_index_path %><br />
    <%= link_to "新着", new_arrivals_index_path %><br />
    <%= link_to "お気に入りの大喜利", my_goods_nices_index_path %><br />

    <% @posts.each do |post| %>
        <div class="post-image">
            <%= link_to image_tag(post.img.to_s, size: "400"), post_path(post) %><br />
        </div>
        <%= link_to post.user.username, user_path(post.user) %>
        <% if current_user.id == post.user.id %>
            <%= link_to post_path(post), method: :delete, data: {confirm: "削除しますか?"} do %>
                <i class="fas fa-times-circle"></i>
            <% end %>
        <% end %>
        <h5><%= post.ogiri %></h5>
        
        <div id="post-like-btn-<%= post.id %>">
            <%= render "goods/good", post: post %>
        </div><br />

        <% post.comments.each do |comment| %>
            <%= comment.ogiri %>
            <small><%= comment.user.username %></small>
            <div id="comment-like-btn-<%= comment.id %>">
                <%= render "nices/nice", comment: comment %>
            </div>
        <% end %>

    <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">    
    <h3>自分で大喜利</h3>
    <%= form_for @post do |f| %>

        <%= f.label :変顔を表示！ %><br />
        <%= f.file_field :img %><br /> 

        <%= f.label :大喜利をしよう！ %><br />
        <%= f.text_field :ogiri, autocomplete: 'off' %>
        
        <%= f.submit :"変顔大喜利を投稿" %>

    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
    <%= image_tag @post.img.to_s %><br /><br />
    <h3>みんなも大喜利してみよう</h3>

    <%= form_for [@post, @comment] do |f| %><br />
        <%= f.text_area :ogiri, size: "40x2" %>
        <%= f.submit '送信', class: "btn-sm btn-primary" %>
    <% end %>

    <%= @post.user.username %><br />
    <h5><%= @post.ogiri %></h5>
    <% if current_user.id == @post.user_id %>
        <%= link_to "編集", edit_post_path(@post) %>
    <% end %><br />
    <% @comments.each do |comment| %>
        <%= comment.ogiri %>
        <small><%= comment.user.username %></small><br />
    <% end %>
    
</div>